### ISSUE TITLE
能发一个成品吗～～

### ISSUE THREAD

**Issue by catbb49294929** [mokyue/Aeciumo#2]
谢谢呢～～毕竟我不会QT

**Comment by catbb49294929** [comment]
编译构建后，登录了也上不了外网～～

**Comment by mokyue** [comment]
`编译构建`后可以运行么？

**Comment by mokyue** [comment]
如果`可以运行`但是`连接不了认证服务器`的话，那应该是`协议问题`，因为这个是在我们学校测试可用，其他内网可能用不同的`外网认证协议`，这个你要了解所在内网的认证系统了。

**Comment by catbb49294929** [comment]
可以，但是不能联外网～～我在男生宿舍这边，认证ip没变～～

**Comment by catbb49294929** [comment]
我们同一个学校～～

**Comment by mokyue** [comment]
![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/fa/lxhtouxiao_thumb.gif) 我擦嘞，你也华软的？

**Comment by catbb49294929** [comment]
Aecium能链接外网～～但三分钟断一次很麻烦，所以看看Aeciumo啦～～是啊，前辈～～

**Comment by mokyue** [comment]
![](![http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/0f/xklyongbao_thumb.gif](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/0f/xklyongbao_thumb.gif)) 但是我已经毕业了，很久以前写的在Linux里用的，不知道现在还能不能用~

**Comment by mokyue** [comment]
![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/6a/laugh.gif) 以前我连一天也没问题的，估计网管那边设置改了什么东西。

**Comment by mokyue** [comment]
![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b6/doge_thumb.gif) 你是软件系的么？如果是的话可以把项目pull下来改善改善的。

**Comment by catbb49294929** [comment]
我也是在linux下编译的，可以运行，嗯，用Aecium启动时多了一个参数 -f ，寻找认证服务用的～～
我看Aeciumo的源码并没有这个参数～～
Aecium运行：
```
Select service:
	1. int
please select(type 'e' to exit):
```
那么问题来了，我想打一个脚本，每三分钟自动重连一次，用while循环，可是怎么输入数字1 ？
```
while true; do
./aecium -h 172.16.1.180 -u username -p password -d wlan0 -f
sleep 180
done
```

**Comment by mokyue** [comment]
是不是每次运行都需要用户输入1这个交互？
如果是shell的话你可以参考这个文章实现自动交互:
[http://os.51cto.com/art/200912/167898.htm](http://os.51cto.com/art/200912/167898.htm "http://os.51cto.com/art/200912/167898.htm")

**Comment by mokyue** [comment]
这个`expect`做交互挺好用的

**Comment by catbb49294929** [comment]
嗷呜～～受教，谢谢～～

**Comment by mokyue** [comment]
![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/b4/lxhbuhaoyisi_thumb.gif)
